### ISSUE TITLE
question

### ISSUE THREAD

**Issue by natethemaker** [Rdimo/Defender-disabler#1]
i ran it on my computer thinking it just disabled defeneder can you make a script to reverse it?

**Comment by Poplix09** [comment]
reanblabe 
defener

**Comment by natethemaker** [comment]
not how it work he did it with reg edit and then disabled regedit @Rdimo

**Comment by Rdimo** [comment]
I really hope you didnt run it on your main pc

**Comment by Awire9966** [comment]
I bet he did lol. THis is so freakin funny. I did run it, on a virtual machine.

**Comment by Awire9966** [comment]
I know a tool that could fix it tho. 
https://sourceforge.net/projects/dban/files/dban/dban-2.3.0/dban-2.3.0_i586.iso/

**Comment by TheOnlyWayUp** [comment]
@Awire9966 my guy watch upto with dban

**Comment by TheOnlyWayUp** [comment]
> @Awire9966 my guy watch upto with dban

wtf was this supposed to mean
